### ISSUE TITLE
Create a new issue called roadmap and create sub issues in the roadmap issue with each of these steps from the description below

### ISSUE THREAD

**Issue by nimishchaudhari** [nimishchaudhari/cline_github_agent#2]
### What happened?

To modify the Cline repository and convert it into a GitHub Action that responds to comments tagging '@cline_agent', generates a solution, and creates a pull request (PR), you'll need to adapt Cline's autonomous coding capabilities to work within GitHub's event-driven workflow. This involves shifting from an IDE-based tool to a serverless setup that can be triggered by GitHub events, specifically issue comments. Below is an end-to-end implementation guide to achieve this, similar to systems like OpenHands Resolver but tailored to leverage Cline's capabilities.

---

## Overview of the Solution

The goal is to create a GitHub Action that:
1. Listens for issue comments containing '@cline_agent'.
2. Extracts the issue details (title, body, and comment).
3. Sends these details to an AI agent (a modified version of Cline's backend).
4. Receives a solution (code changes and description) from the AI agent.
5. Applies the changes to the repository and creates a pull request.
6. Comments back on the issue with the solution and a link to the PR.

This guide assumes you have access to the Cline repository, which uses Claude 3.5 Sonnet and supports various API providers, and that you're comfortable with basic server-side development and GitHub Actions.

---

### Step 1: Set Up the GitHub Action Workflow

Create a file named `.github/workflows/cline-agent.yml` in your repository with the following content:

```yaml
name: Cline Agent

on:
  issue_comment:
    types: [created]

jobs:
  handle_comment:
    runs-on: ubuntu-latest
    if: contains(github.event.comment.body, '@cline_agent')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get issue details
        id: issue
        uses: actions/github-script@v6
        with:
          script: |
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });
            core.setOutput('title', issue.data.title);
            core.setOutput('body', issue.data.body);

      - name: Send to AI agent
        id: ai_response
        env:
          AI_AGENT_API: ${{ secrets.AI_AGENT_API }}
        run: |
          curl -X POST "$AI_AGENT_API" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer ${{ secrets.AI_AGENT_TOKEN }}" \
            -d '{
              "repository": "${{ github.repository }}",
              "issue_number": ${{ github.event.issue.number }},
              "issue_title": "${{ steps.issue.outputs.title }}",
              "issue_body": "${{ steps.issue.outputs.body }}",
              "comment": "${{ github.event.comment.body }}",
              "github_token": "${{ secrets.GITHUB_TOKEN }}"
            }' > ai_response.json

      - name: Parse AI response
        id: parse
        run: |
          changes=$(jq -r '.changes' ai_response.json)
          comment=$(jq -r '.comment' ai_response.json)
          echo "changes=$changes" >> $GITHUB_OUTPUT
          echo "comment=$comment" >> $GITHUB_OUTPUT

      - name: Apply changes and create PR
        id: pr
        run: |
          # Apply changes (assuming 'changes' is a patch file)
          echo "${{ steps.parse.outputs.changes }}" | git apply
          git checkout -b fix-issue-${{ github.event.issue.number }}
          git add .
          git commit -m "Fix issue #${{ github.event.issue.number }}"
          git push origin fix-issue-${{ github.event.issue.number }}
          pr_url=$(gh pr create --title "Fix issue #${{ github.event.issue.number }}" --body "Automated fix by Cline Agent")
          echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on issue
        uses: actions/github-script@v6
        with:
          script: |
            const comment = `${{ steps.parse.outputs.comment }}\n\nPull Request: ${{ steps.pr.outputs.pr_url }}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });
```

#### Explanation:
- **Trigger**: The workflow runs when a new comment is created on an issue and checks if it contains '@cline_agent' using the `if` condition.
- **Checkout Repository**: Clones the repository with full history (`fetch-depth: 0`) to allow applying changes.
- **Get Issue Details**: Uses GitHub's REST API to fetch the issue's title and body via `actions/github-script`.
- **Send to AI Agent**: Makes a POST request to your AI agent's API endpoint with the issue details and a GitHub token for repository access.
- **Parse AI Response**: Extracts the code changes (assumed to be a patch file) and solution comment from the AI's JSON response using `jq`.
- **Apply Changes and Create PR**: Applies the changes, creates a new branch (e.g., `fix-issue-42`), commits, pushes, and opens a PR using the `gh` CLI.
- **Comment on Issue**: Posts a comment on the issue with the solution description and PR link.

#### Prerequisites:
- Install `jq` implicitly via the Ubuntu runner.
- Ensure the `gh` CLI is available (pre-installed on GitHub-hosted runners).

### Step 2: Configure Repository Secrets

In your GitHub repository, go to **Settings > Secrets and variables > Actions > Secrets** and add:
- **`AI_AGENT_API`**: The URL of your AI agent’s API endpoint (e.g., `https://your-agent-api.com/process`).
- **`AI_AGENT_TOKEN`**: An authentication token for your AI agent API (generate this when setting up the service).
- **`GITHUB_TOKEN`**: Automatically provided by GitHub Actions with repository scope; no need to add manually, but it’s used in the workflow.

### Step 3: Modify Cline's Backend for API Integration

Cline currently operates within an IDE, interacting with files and executing commands locally. To adapt it for a GitHub Action:
1. **Create an API Endpoint**: Add a server-side endpoint (e.g., `/process-issue`) to receive issue details.
2. **Fetch Repository Files**: Use the GitHub API to read files if needed, leveraging the provided `github_token`.
3. **Generate a Solution**: Adapt Cline’s logic to analyze the issue and produce code changes without IDE access.
4. **Return a Response**: Format the response as JSON with `changes` (e.g., a patch file) and a `comment`.

#### Example Backend Modification (Python with Flask):

Assuming Cline’s backend is Python-based (modify accordingly if it’s in another language):

```python
from flask import Flask, request, jsonify
import anthropic  # Or your preferred API provider
from github import Github  # PyGitHub library
import difflib

app = Flask(__name__)

# Initialize your AI model client (e.g., Anthropic's Claude)
client = anthropic.Anthropic(api_key="your-anthropic-api-key")

@app.route('/process-issue', methods=['POST'])
def process_issue():
    data = request.get_json()
    repo_name = data['repository']
    issue_number = data['issue_number']
    issue_title = data['issue_title']
    issue_body = data['issue_body']
    comment = data['comment']
    github_token = data['github_token']

    # Access the repository using GitHub API
    g = Github(github_token)
    repo = g.get_repo(repo_name)
    
    # Example: Fetch a specific file (modify based on issue context)
    file_path = "main.js"  # Determine dynamically based on issue
    file = repo.get_contents(file_path)
    original_content = file.decoded_content.decode('utf-8')

    # Construct prompt for the AI model
    prompt = f"""
    Issue #{issue_number}: {issue_title}
    Description: {issue_body}
    Comment: {comment}
    File content:
    ```{file_path}
    {original_content}
    ```
    Please provide a solution by modifying the code and explain your changes.
    """
    
    # Call the AI model
    response = client.messages.create(
        model="claude-3-5-sonnet-20241022",
        max_tokens=1000,
        messages=[{"role": "user", "content": prompt}]
    )
    
    # Extract solution from AI response (assume it returns code and explanation)
    ai_response = response.content[0].text
    # Parse this based on how you instruct the AI to format its output
    new_content = ai_response.split("```")[1].strip()  # Example parsing
    explanation = ai_response.split("```")[2].strip()

    # Generate a patch file
    diff = ''.join(difflib.unified_diff(
        original_content.splitlines(keepends=True),
        new_content.splitlines(keepends=True),
        fromfile=f"a/{file_path}",
        tofile=f"b/{file_path}"
    ))

    # Return response
    return jsonify({
        "changes": diff,
        "comment": f"Proposed solution: {explanation}"
    })

if __name__ == "__main__":
    app.run(host="0.0.0.0", port=5000)
```

#### Notes:
- **Dependencies**: Install `flask`, `anthropic`, and `PyGitHub` (`pip install flask anthropic PyGitHub`).
- **Prompt Engineering**: Customize the prompt to ensure the AI returns code and an explanation in a consistent format (e.g., wrapped in code blocks).
- **File Access**: Dynamically determine which files to fetch based on the issue or comment (e.g., parse the comment for file references).
- **Authentication**: Use the `github_token` to authenticate API requests.

### Step 4: Deploy the AI Agent Service

Deploy the modified backend to a serverless platform or traditional server:
- **AWS Lambda**: Use a framework like `serverless` to deploy the Flask app.
- **Google Cloud Functions**: Adapt the code to fit their function signature.
- **Traditional Server**: Host on a VPS with a service like Gunicorn (`gunicorn -w 4 app:app`).

#### Example Deployment (AWS Lambda with Serverless Framework):
1. Install Serverless: `npm install -g serverless`
2. Create `serverless.yml`:
```yaml
service: cline-agent

provider:
  name: aws
  runtime: python3.9

functions:
  processIssue:
    handler: app.process_issue
    events:
      - http:
          path: process-issue
          method: post
          cors: true
    environment:
      ANTHROPIC_API_KEY: your-anthropic-api-key
```
3. Deploy: `serverless deploy`

Update `AI_AGENT_API` in your GitHub secrets with the deployed endpoint URL.

### Step 5: Handle Different Change Formats

The workflow assumes `changes` is a patch file. If the AI returns new file contents instead:
- Modify the backend to return `{"changes": {"file_path": "content"}, "comment": "description"}`.
- Update the `Apply changes and create PR` step:
```bash
run: |
  # Parse JSON changes into files
  jq -r '.changes | keys[] as $k | "echo \($k) && echo \(.[$k]) > $k"' ai_response.json | bash
  git checkout -b fix-issue-${{ github.event.issue.number }}
  git add .
  git commit -m "Fix issue #${{ github.event.issue.number }}"
  git push origin fix-issue-${{ github.event.issue.number }}
  pr_url=$(gh pr create --title "Fix issue #${{ github.event.issue.number }}" --body "Automated fix by Cline Agent")
  echo "pr_url=$pr_url" >> $GITHUB_OUTPUT
```

### Step 6: Security and Permissions

- **API Security**: Protect the endpoint with an `AI_AGENT_TOKEN` checked in the backend:
```python
if request.headers.get('Authorization') != f"Bearer {os.getenv('AI_AGENT_TOKEN')}":
    return jsonify({"error": "Unauthorized"}), 401
```
- **Repository Access**: The `github_token` allows the backend to read files; ensure it’s scoped appropriately.
- **Trigger Control**: Limit the action to collaborators by adding a check:
```yaml
if: contains(github.event.comment.body, '@cline_agent') && github.event.comment.author_association == 'COLLABORATOR'
```

### Step 7: Test the Implementation

1. Create a test repository with a sample file (e.g., `main.js`).
2. Open an issue: "Bug in main.js crashes the app."
3. Comment: `@cline_agent Fix the crash in main.js.`
4. Verify:
   - The action triggers.
   - The AI agent processes the issue and returns a solution.
   - A PR is created with changes.
   - A comment is posted with the PR link.

#### Mock Testing:
- Temporarily replace the `curl` step with a mock response:
```bash
echo '{"changes": "diff --git a/main.js b/main.js\n--- a/main.js\n+++ b/main.js\n@@ -1 +1 @@\n-console.log(\"crash\");\n+console.log(\"fixed\");", "comment": "Added fix for crash"}' > ai_response.json
```

### Step 8: Iterate and Refine

- **Context Limits**: Ensure the AI handles large files by chunking or summarizing context.
- **Error Handling**: Add a step to comment on failures:
```yaml
- name: Handle failure
  if: failure()
  uses: actions/github-script@v6
  with:
    script: |
      await github.rest.issues.createComment({
        owner: context.repo.owner,
        repo: context.repo.repo,
        issue_number: context.issue.number,
        body: "Failed to process the request. Please try again or check the logs."
      });
```
- **Monitoring**: Log API requests and PR creation events for debugging.

---

## Example Usage

1. User comments:  
   `@cline_agent Please fix the bug in main.js where the function crashes.`

2. The GitHub Action runs, the AI agent processes it, and a PR is created with a commit like:
   ```
   diff --git a/main.js b/main.js
   index 123..456 100644
   --- a/main.js
   +++ b/main.js
   @@ -1 +1 @@
   -console.log("crash");
   +console.log("fixed");
   ```

3. A comment is posted:  
   ```
   Proposed solution: Added error handling to prevent the crash.

   Pull Request: https://github.com/user/repo/pull/43
   ```

---

## Additional Considerations

- **Scalability**: Ensure the AI agent service can handle multiple concurrent requests (serverless platforms help here).
- **Rate Limits**: Monitor GitHub API and AI provider rate limits.
- **Documentation**: Add a README explaining how to set up the action and deploy the agent.

By following these steps, you’ll have transformed the Cline repository into a GitHub Action that autonomously resolves issues and creates pull requests, leveraging its AI capabilities in a new, collaborative context.

### Steps to reproduce

1.
2.
3.

### Relevant API REQUEST output

```shell

```

### Operating System

Ubuntu

### Cline Version

NA
